### ISSUE TITLE
Build fails in WSL

### ISSUE THREAD

**Issue by kirilan** [ItzCrazyKns/Perplexica#104]
**Describe the bug**
Build fails in Windows WSL with default settings

**To Reproduce**

clone the repo in WSL (ubuntu server 22.04) edit the config and only add the default ollama URL (or localhost for that matter)

**Expected behavior**
I expect to build and start the docker containers

**Screenshots**
logs below

**Additional context**
kiril@ROGM16:/mnt/c/Users/kiril/Perplexica$ docker compose up -d
[+] Building 17.8s (9/9) FINISHED                                                                        docker:default
 => [perplexica-frontend internal] load build definition from app.dockerfile                                       0.0s
 => => transferring dockerfile: 308B                                                                               0.0s
 => [perplexica-frontend internal] load metadata for docker.io/library/node:alpine                                 0.7s
 => [perplexica-frontend internal] load .dockerignore                                                              0.0s
 => => transferring context: 55B                                                                                   0.0s
 => [perplexica-frontend 1/5] FROM docker.io/library/node:alpine@sha256:916b42f9e83466eb17d60a441a96f5cd57033bbfe  0.0s
 => [perplexica-frontend internal] load build context                                                              0.1s
 => => transferring context: 259.35kB                                                                              0.1s
 => CACHED [perplexica-frontend 2/5] WORKDIR /home/perplexica                                                      0.0s
 => CACHED [perplexica-frontend 3/5] COPY ui /home/perplexica/                                                     0.0s
 => CACHED [perplexica-frontend 4/5] RUN yarn install                                                              0.0s
 => ERROR [perplexica-frontend 5/5] RUN yarn build                                                                16.9s
------
 > [perplexica-frontend 5/5] RUN yarn build:
0.294 yarn run v1.22.19
0.312 $ next build
0.695 Attention: Next.js now collects completely anonymous telemetry regarding usage.
0.695 This information is used to shape Next.js' roadmap and prioritize features.
0.695 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
0.695 https://nextjs.org/telemetry
0.695
0.760    ▲ Next.js 14.1.4
0.760
0.811    Creating an optimized production build ...
1.952 (node:41) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
1.952 (Use `node --trace-deprecation ...` to show where the warning was created)
8.323 (node:127) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
8.323 (Use `node --trace-warnings ...` to show where the warning was created)
8.576 (node:127) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
13.33  ✓ Compiled successfully
13.33    Linting and checking validity of types ...
15.89    Collecting page data ...
16.53    Generating static pages (0/6) ...
   Generating static pages (1/6)
   Generating static pages (2/6)
   Generating static pages (4/6)
16.77  ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
16.77     at a (/home/perplexica/.next/server/chunks/853.js:46:11063)
16.77     at m (/home/perplexica/.next/server/chunks/853.js:46:22816)
16.77     at lt (/home/perplexica/.next/server/app/page.js:20:48143)
16.77     at nM (/home/perplexica/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47422)
16.77     at nM (/home/perplexica/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61666)
16.77     at nL (/home/perplexica/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64677)
16.77     at nB (/home/perplexica/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67660)
16.77     at nM (/home/perplexica/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:58554)
16.77     at nL (/home/perplexica/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64677)
16.77     at nB (/home/perplexica/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67660)
16.77
16.77 Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
16.77
 ✓ Generating static pages (6/6)
16.79
16.79 > Export encountered errors on following paths:
16.79   /page: /
16.83 error Command failed with exit code 1.
16.83 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1
kiril@ROGM16:/mnt/c/Users/kiril/Perplexica$

**Comment by ItzCrazyKns** [comment]
Fixed in https://github.com/ItzCrazyKns/Perplexica/commit/c852bee8ed99092d7956b913bdd611ddb8eca300

**Comment by kirilan** [comment]
weirdly enough I still get the same error. but maybe some cache caused me to download the older version. I will give it a bit of time and try again

**Comment by kirilan** [comment]
actually it now builds normally on WSL, but it fails on Debian which is probably a completely separate issue.

Thank you @ItzCrazyKns
