### ISSUE TITLE
Axios exception broke backend, and also broke thread

### ISSUE THREAD

**Issue by aledalgrande** [ItzCrazyKns/Perplexica#368]
**Describe the bug**

I was in a 4-5 messages deep search thread and at a certain point the loading icon kept spinning with no result. So I looked in the BE logs and I found:
```
error: Unhandled Rejection at: [object Promise], reason: AxiosError: Request failed with status code 400
error: Unhandled Rejection at: [object Promise], reason: AxiosError: Request failed with status code 400
```

I decided to restart that docker container. Then I refreshed the browser page and the UI was broken because I didn't have an input field any more so I couldn't continue the conversation. Even if I go to a new conversation and then visit the history and reopen this thread I cannot continue it.

I tried "rewrite" and that also failed.

New threads work normally.

**To Reproduce**

Unfortunately I don't know how to reproduce this. I am using Ollama with Llama 3.1 8B on a M1 Max 64GB. I think in dev it might be possible by trying to recreate a failed network request for the BE container/service.

**Expected behavior**

Ideally, a network issue would stop the loader state and show an error and allow to retry. Also threads shouldn't get into a broken state.

**Screenshots**

See empty bottom of the page:
<img width="711" alt="Screenshot 2024-09-21 at 4 35 46 PM" src="https://github.com/user-attachments/assets/95c59391-d73b-422d-957a-f94d46167576">

**Comment by ItzCrazyKns** [comment]
Rewrite has been fixed in the latest commits, can you try creating a new chat and see if that works. (After updating)

**Comment by ironicbadger** [comment]
Using the example docker-compose.yaml I still see similar behavior.

```
perplexica-backend-1   | error: Unhandled Rejection at: [object Promise], reason: AxiosError: Request failed with status code 403
perplexica-backend-1   | error: Error in image search: Request failed with status code 403
perplexica-backend-1   | error: Unhandled Rejection at: [object Promise], reason: AxiosError: Request failed with status code 403
```

The chat just hangs until refreshed or a new chat is started. Happens most chats after 2-3+ responses.

**Comment by ItzCrazyKns** [comment]
What are the logs from SearXNG?

> Using the example docker-compose.yaml I still see similar behavior.
> 
> ```
> perplexica-backend-1   | error: Unhandled Rejection at: [object Promise], reason: AxiosError: Request failed with status code 403
> perplexica-backend-1   | error: Error in image search: Request failed with status code 403
> perplexica-backend-1   | error: Unhandled Rejection at: [object Promise], reason: AxiosError: Request failed with status code 403
> ```
> 
> The chat just hangs until refreshed or a new chat is started. Happens most chats after 2-3+ responses.
