### ISSUE TITLE
work  well on localhost:3000 url , error on remote:3000

### ISSUE THREAD

**Issue by perlinson** [ItzCrazyKns/Perplexica#50]
**Describe the bug**
work on localhost:3000port , when i use a domain:3000 , on remote pc ,it not work , i use local ollama 
**To Reproduce**

1. F12

**Expected behavior**

**Screenshots**
<img width="451" alt="image" src="https://github.com/ItzCrazyKns/Perplexica/assets/6311926/63ca7868-25b1-4011-995e-9bfef71ca185">
**Additional context**

**Comment by ItzCrazyKns** [comment]
You need to change the IP in the docker-compose file to the private IP of the server where you deployed Perplexica.

**Comment by futurewin** [comment]
i used Non-Docker Installation to install Perplexica , i don't know how to fix this problem. and i used docker to install it again, then have another problem 

yarn run v1.22.19
$ node dist/app.js
info: WebSocket server started on port 3001
(node:28) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info: Server is running on port 3001

**Comment by perlinson** [comment]
which one  to change and where to change?

**Comment by perlinson** [comment]
<img width="468" alt="image" src="https://github.com/ItzCrazyKns/Perplexica/assets/6311926/65743ff4-6bc0-4665-bd95-2724142fd434">
here?

**Comment by ItzCrazyKns** [comment]
> <img alt="image" width="468" src="https://private-user-images.githubusercontent.com/6311926/327623565-65743ff4-6bc0-4665-bd95-2724142fd434.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2OTg2MzEsIm5iZiI6MTcxNDY5ODMzMSwicGF0aCI6Ii82MzExOTI2LzMyNzYyMzU2NS02NTc0M2ZmNC02YmMwLTQ2NjUtYmQ5NS0yNzI0MTQyZmQ0MzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDNUMDEwNTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTk1NDcyODAzNDU4ZWIyZjlmNTBjYTY0ZDI5Yzg0MThmMjQyZWZlYzcwMTlkZGM5MDgwZTYwMDlhMGU0ZmQ4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Xym44Wc5GpB2RBosHz2hR0oeGdxqi_aQUFnk608a-ko"> here?

Looks perfect

**Comment by perlinson** [comment]
<img width="899" alt="image" src="https://github.com/ItzCrazyKns/Perplexica/assets/6311926/2277b310-c209-4063-9254-9f082887c591">
it got this problem 

by the way 
<img width="442" alt="image" src="https://github.com/ItzCrazyKns/Perplexica/assets/6311926/4cce5e9d-b92c-4203-bd2b-d1dcc55b835a">  this proxy setting work well, but  it's wrong when i use the 
- HTTP_PROXY=http://host.docker.internal:7890 
        - HTTPS_PROXY=http://host.docker.internal:7890 
        - ALL_PROXY=socks5://host.docker.internal:7890.    it say unsolved address host.docker.internal , how to solve this problem, i want to use my pc's 7890 port  for proxy , not the lan pc 7890 port

**Comment by perlinson** [comment]
i was using ubuntu 22.04 os

**Comment by perlinson** [comment]
i was solve the proxy problem, just left the "Access-Control-Allow-Origin" problem

**Comment by ItzCrazyKns** [comment]
I've already implemented CORS on the backend server, so it should not produce errors like this. We only provide installation support in Perplexica. If you wish to expose it to your network, you should have sufficient knowledge to do so on your own, and therefore, we cannot assist you with that.

**Comment by lzmfor** [comment]
Sorry, I still get trouble at this issue. I have changed ip, but still can't access it from another pc on the LAN. (Home page keeps loading) 

```
... ...
  - NEXT_PUBLIC_API_URL=http://192.168.31.19:3001/api
  - NEXT_PUBLIC_WS_URL=ws://192.168.31.19:3001
... ...
```
- `docker-compose.yaml`
```
services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - perplexica-network

  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
    ports:
      - 3001:3001
    networks:
      - perplexica-network

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://192.168.31.19:3001/api
        - NEXT_PUBLIC_WS_URL=ws://192.168.31.19:3001
    depends_on:
      - perplexica-backend
    ports:
      - 3000:3000
    networks:
      - perplexica-network

networks:
  perplexica-network:
```
